#!/usr/bin/env bash

# Run your display executables through this centralized bash script to reduce flicker from:
#   1. Improved linux process priority
#   2. Optimizing execution by pinning CPU to one thread (prevent thread-switching and kernel-interupts)
cwd=$(pwd)

cd /home/led-matrix/RPI-RGB-Matrix/examples-api-use
chrt -f 90 taskset -c 3 ./gta-countdown --led-cols=64 --led-rows=64 --led-no-hardware-pulse --led-daemon
cd $cwd